name: OpenSSF Scorecard

on: [push]

jobs:
  scorecard:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v3

      - name: Run OpenSSF Scorecard
        uses: ossf/scorecard-action@v2
        with:
          repo: ${{ github.repository }}
          github_token: ${{ secrets.GITHUB_TOKEN }}
          format: json
